repos:
  - repo: local
    hooks:
      - id: server-ruff-fix-and-format
        name: server ruff check and format
        entry: sh code/server/scripts/pre-commit.sh
        language: system
        pass_filenames: false
        always_run: true
        files: ^code/server/src/