import pytest
from pydantic import ValidationError

from phylo_lens_server.data.normalizer import NormalizeRequest, normalize_dataset
from phylo_lens_server.domain.ancillary import AncillarySummary, ProfileSummary
from phylo_lens_server.domain.legacy_metadata import (
    decode_node_annotations,
    encode_node_annotations,
)
from phylo_lens_server.domain.models import CanonicalDataset, Isolate
from phylo_lens_server.http.graph.schemas import GraphViewportNode
from phylo_lens_server.pipeline.ingest import layout_version_for_dataset


def test_legacy_annotations_round_trip_without_mixing_user_and_generated_fields():
    legacy = {
        "country": "PT;ES",
        "year": None,
        "profile_count": 3.0,
        "__category_count__country__value__PT": 2.0,
        "__category_count__country__value__ES": 1.0,
    }
    node = decode_node_annotations(legacy)
    assert node.ancillary_data == {}
    assert node.ancillary_summary.values == {"country": "PT;ES", "year": None}
    assert node.ancillary_summary.category_counts == {"country": {"PT": 2, "ES": 1}}
    assert node.profile_summary.isolate_count == 3
    assert encode_node_annotations(node) == legacy
    assert decode_node_annotations({}).profile_summary.isolate_count is None


@pytest.mark.parametrize("invalid", [0, -1, 1.5, True, float("inf"), float("nan")])
def test_summary_counts_are_positive_integers(invalid):
    with pytest.raises((ValueError, ValidationError)):
        decode_node_annotations({"profile_count": invalid})
    with pytest.raises(ValidationError):
        ProfileSummary(isolate_count=invalid)
    with pytest.raises(ValidationError):
        AncillarySummary(category_counts={"country": {"PT": invalid}})


def test_isolate_uses_ancillary_data_in_domain_and_metadata_only_on_v1_wire():
    isolate = Isolate(id="original-id", ancillary_data={"country": "PT"})
    assert isolate.model_dump() == {
        "id": "original-id",
        "ancillary_data": {"country": "PT"},
    }
    node = GraphViewportNode(
        id="profile",
        cluster_id="profile",
        x=0,
        y=0,
        layout_status="ready",
        isolates=[isolate],
    )
    assert node.model_dump(by_alias=True)["isolates"] == [
        {"id": "original-id", "metadata": {"country": "PT"}}
    ]


def test_new_and_deprecated_request_names_normalize_identically():
    common = {"format": "newick", "content": "(a:1,b:2)root;"}
    values = {"a": {"country": "PT"}}
    fields = [{"key": "country", "type": "string"}]
    current = normalize_dataset(
        NormalizeRequest(**common, ancillary_schema=fields, ancillary_by_node_id=values)
    ).dataset
    legacy = normalize_dataset(
        NormalizeRequest(**common, metadata_schema=fields, metadata_by_node_id=values)
    ).dataset
    assert current.annotations_by_node_id == legacy.annotations_by_node_id
    assert current.ancillary_schema == legacy.ancillary_schema
    assert layout_version_for_dataset(current) == layout_version_for_dataset(legacy)
    assert (
        CanonicalDataset.model_validate(current.model_dump()).annotations_by_node_id
        == current.annotations_by_node_id
    )
    with pytest.raises(ValidationError, match="not both"):
        NormalizeRequest(**common, ancillary_schema=fields, metadata_schema=fields)


def test_refactor_preserves_preexisting_layout_fingerprint():
    # Baseline generated by commit 868453e before separating domain annotations.
    request = NormalizeRequest(
        format="newick",
        dataset_name="compatibility",
        content="(a:1,b:2)root;",
        ancillary_data={
            "content": "id\tcountry\na\tPT\na\tES\nb\tPT\n",
            "join_column": "id",
            "format": "tsv",
        },
    )
    dataset = normalize_dataset(request, expose_internal_schema=True).dataset
    assert [field.key for field in dataset.ancillary_schema] == ["country"]
    assert dataset.annotations_by_node_id["a"].profile_summary.isolate_count == 2
    assert layout_version_for_dataset(dataset) == "ad770f6c2200bfac"
